/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testmontag;

import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.*;

import java.io.FileOutputStream;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

            // Erstelle ein Workbook (Excel-Datei)
            Workbook workbook = new XSSFWorkbook();
                    
            // Erstelle ein Sheet
            Sheet sheet = workbook.createSheet("Jaleban Jeevarajah");

            // Erstelle eine Row (Zeile)
            Row row = sheet.createRow(0);

            // Erstelle eine Cell (Zelle) und füge einen Text hinzu
            Cell cell = row.createCell(0);
            cell.setCellValue("Hallo Jaleban!");

            // Schreibe das Workbook in eine Datei
            try (FileOutputStream outputStream = new FileOutputStream("jeevajalExcel.xlsx")) {
                workbook.write(outputStream);
                workbook.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
    }
}
